"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-07-18 16:06:41.392341
"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "companies",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=160), nullable=False),
        sa.Column("slug", sqlmodel.sql.sqltypes.AutoString(length=180), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_system", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_companies_name"), "companies", ["name"], unique=False)
    op.create_index(op.f("ix_companies_slug"), "companies", ["slug"], unique=True)
    op.create_table(
        "question_tags",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column("slug", sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
        sa.Column("category", sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_question_tags_category"), "question_tags", ["category"], unique=False)
    op.create_index(op.f("ix_question_tags_name"), "question_tags", ["name"], unique=True)
    op.create_index(op.f("ix_question_tags_slug"), "question_tags", ["slug"], unique=True)
    op.create_table(
        "user_profiles",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("display_name", sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
        sa.Column("locale", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
        sa.Column("timezone", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column("preferences", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("memory_enabled", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "background_jobs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("profile_id", sa.Uuid(), nullable=True),
        sa.Column("job_type", sa.String(length=48), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("progress", sa.Float(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("error_code", sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("idempotency_key", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("locked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("locked_by", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.ForeignKeyConstraint(["profile_id"], ["user_profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_background_jobs_available_at"), "background_jobs", ["available_at"], unique=False
    )
    op.create_index(
        op.f("ix_background_jobs_idempotency_key"),
        "background_jobs",
        ["idempotency_key"],
        unique=True,
    )
    op.create_index(
        op.f("ix_background_jobs_job_type"), "background_jobs", ["job_type"], unique=False
    )
    op.create_index(
        op.f("ix_background_jobs_profile_id"), "background_jobs", ["profile_id"], unique=False
    )
    op.create_index(op.f("ix_background_jobs_status"), "background_jobs", ["status"], unique=False)
    op.create_table(
        "company_style_packs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=160), nullable=False),
        sa.Column("pack_version", sa.Integer(), nullable=False),
        sa.Column("supported_roles", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "default_interviewer_behavior", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("field_confidence", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("visibility", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("company_id", "pack_version", name="uq_style_pack_version"),
    )
    op.create_index(
        op.f("ix_company_style_packs_company_id"),
        "company_style_packs",
        ["company_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_company_style_packs_status"), "company_style_packs", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_company_style_packs_visibility"),
        "company_style_packs",
        ["visibility"],
        unique=False,
    )
    op.create_table(
        "memory_items",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("profile_id", sa.Uuid(), nullable=False),
        sa.Column("memory_type", sa.String(length=48), nullable=False),
        sa.Column("canonical_key", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("memory_version", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("structured_value", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("first_observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("pinned", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["profile_id"], ["user_profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "profile_id", "canonical_key", "memory_version", name="uq_memory_item_version"
        ),
    )
    op.create_index(
        op.f("ix_memory_items_canonical_key"), "memory_items", ["canonical_key"], unique=False
    )
    op.create_index(
        op.f("ix_memory_items_memory_type"), "memory_items", ["memory_type"], unique=False
    )
    op.create_index(op.f("ix_memory_items_pinned"), "memory_items", ["pinned"], unique=False)
    op.create_index(
        op.f("ix_memory_items_profile_id"), "memory_items", ["profile_id"], unique=False
    )
    op.create_index(op.f("ix_memory_items_status"), "memory_items", ["status"], unique=False)
    op.create_table(
        "model_connections",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("profile_id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
        sa.Column("provider_type", sa.String(length=32), nullable=False),
        sa.Column("base_url", sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=False),
        sa.Column("encrypted_api_key", sa.Text(), nullable=True),
        sa.Column("model_name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column(
            "extra_headers_encrypted", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("context_window_tokens", sa.Integer(), nullable=False),
        sa.Column("max_output_tokens", sa.Integer(), nullable=False),
        sa.Column("tokenizer_type", sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
        sa.Column("supports_prompt_caching", sa.Boolean(), nullable=False),
        sa.Column("supports_token_count_endpoint", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(["profile_id"], ["user_profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("profile_id", "name", name="uq_model_connection_name"),
    )
    op.create_index(
        op.f("ix_model_connections_model_name"), "model_connections", ["model_name"], unique=False
    )
    op.create_index(
        op.f("ix_model_connections_profile_id"), "model_connections", ["profile_id"], unique=False
    )
    op.create_index(
        op.f("ix_model_connections_provider_type"),
        "model_connections",
        ["provider_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_model_connections_status"), "model_connections", ["status"], unique=False
    )
    op.create_table(
        "question_banks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("profile_id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=160), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("visibility", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(["profile_id"], ["user_profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("profile_id", "name", name="uq_question_bank_name"),
    )
    op.create_index(
        op.f("ix_question_banks_profile_id"), "question_banks", ["profile_id"], unique=False
    )
    op.create_index(
        op.f("ix_question_banks_visibility"), "question_banks", ["visibility"], unique=False
    )
    op.create_table(
        "resumes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("profile_id", sa.Uuid(), nullable=False),
        sa.Column("filename", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("mime_type", sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
        sa.Column("storage_path", sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
        sa.Column("content_hash", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
        sa.Column("parse_status", sa.String(length=32), nullable=False),
        sa.Column("parsed_text", sa.Text(), nullable=True),
        sa.Column("parse_error_code", sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
        sa.ForeignKeyConstraint(["profile_id"], ["user_profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_resumes_content_hash"), "resumes", ["content_hash"], unique=False)
    op.create_index(op.f("ix_resumes_parse_status"), "resumes", ["parse_status"], unique=False)
    op.create_index(op.f("ix_resumes_profile_id"), "resumes", ["profile_id"], unique=False)
    op.create_table(
        "evidence_items",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("style_pack_id", sa.Uuid(), nullable=False),
        sa.Column("source_url", sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=False),
        sa.Column("source_title", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
        sa.Column("field_path", sqlmodel.sql.sqltypes.AutoString(length=240), nullable=False),
        sa.Column("excerpt", sa.Text(), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("source_hash", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
        sa.ForeignKeyConstraint(["style_pack_id"], ["company_style_packs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_evidence_items_field_path"), "evidence_items", ["field_path"], unique=False
    )
    op.create_index(
        op.f("ix_evidence_items_source_hash"), "evidence_items", ["source_hash"], unique=False
    )
    op.create_index(
        op.f("ix_evidence_items_style_pack_id"), "evidence_items", ["style_pack_id"], unique=False
    )
    op.create_table(
        "memory_conflicts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("memory_id", sa.Uuid(), nullable=False),
        sa.Column("conflicting_memory_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("resolution", sa.Text(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["conflicting_memory_id"], ["memory_items.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["memory_id"], ["memory_items.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("memory_id", "conflicting_memory_id", name="uq_memory_conflict_pair"),
    )
    op.create_index(
        op.f("ix_memory_conflicts_conflicting_memory_id"),
        "memory_conflicts",
        ["conflicting_memory_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_memory_conflicts_memory_id"), "memory_conflicts", ["memory_id"], unique=False
    )
    op.create_index(
        op.f("ix_memory_conflicts_status"), "memory_conflicts", ["status"], unique=False
    )
    op.create_table(
        "model_role_bindings",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("profile_id", sa.Uuid(), nullable=False),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.Column("connection_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["connection_id"], ["model_connections.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["profile_id"], ["user_profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("profile_id", "role", name="uq_model_role_binding"),
    )
    op.create_index(
        op.f("ix_model_role_bindings_connection_id"),
        "model_role_bindings",
        ["connection_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_model_role_bindings_profile_id"),
        "model_role_bindings",
        ["profile_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_model_role_bindings_role"), "model_role_bindings", ["role"], unique=False
    )
    op.create_table(
        "questions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("bank_id", sa.Uuid(), nullable=False),
        sa.Column("prompt", sa.Text(), nullable=False),
        sa.Column("question_type", sa.String(length=32), nullable=False),
        sa.Column("difficulty", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("reference_points", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("follow_up_suggestions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("applicable_companies", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("applicable_rounds", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("source_type", sa.String(length=32), nullable=False),
        sa.Column("source_note", sa.Text(), nullable=True),
        sa.Column("user_note", sa.Text(), nullable=True),
        sa.Column("normalized_hash", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
        sa.Column("times_used", sa.Integer(), nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["bank_id"], ["question_banks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("bank_id", "normalized_hash", name="uq_question_bank_hash"),
    )
    op.create_index(op.f("ix_questions_bank_id"), "questions", ["bank_id"], unique=False)
    op.create_index(op.f("ix_questions_difficulty"), "questions", ["difficulty"], unique=False)
    op.create_index(
        op.f("ix_questions_normalized_hash"), "questions", ["normalized_hash"], unique=False
    )
    op.create_index(
        op.f("ix_questions_question_type"), "questions", ["question_type"], unique=False
    )
    op.create_index(op.f("ix_questions_source_type"), "questions", ["source_type"], unique=False)
    op.create_index(op.f("ix_questions_status"), "questions", ["status"], unique=False)
    op.create_table(
        "resume_sections",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("resume_id", sa.Uuid(), nullable=False),
        sa.Column("section_type", sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
        sa.Column("heading", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("section_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(["resume_id"], ["resumes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("resume_id", "sequence", name="uq_resume_section_sequence"),
    )
    op.create_index(
        op.f("ix_resume_sections_resume_id"), "resume_sections", ["resume_id"], unique=False
    )
    op.create_index(
        op.f("ix_resume_sections_section_type"), "resume_sections", ["section_type"], unique=False
    )
    op.create_table(
        "round_profiles",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("style_pack_id", sa.Uuid(), nullable=False),
        sa.Column("round_key", sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("opening_style", sa.Text(), nullable=True),
        sa.Column("topic_weights", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("follow_up_patterns", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("pressure_level", sa.Integer(), nullable=False),
        sa.Column("answer_expectations", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("evaluation_weights", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("duration_minutes", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["style_pack_id"], ["company_style_packs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("style_pack_id", "round_key", name="uq_round_profile_key"),
    )
    op.create_index(
        op.f("ix_round_profiles_style_pack_id"), "round_profiles", ["style_pack_id"], unique=False
    )
    op.create_table(
        "interview_configs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("profile_id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("round_profile_id", sa.Uuid(), nullable=False),
        sa.Column("resume_id", sa.Uuid(), nullable=True),
        sa.Column("role_name", sqlmodel.sql.sqltypes.AutoString(length=160), nullable=False),
        sa.Column("duration_minutes", sa.Integer(), nullable=False),
        sa.Column("target_question_count", sa.Integer(), nullable=False),
        sa.Column("question_bank_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("source_weights", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("preferences", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["profile_id"], ["user_profiles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["resume_id"], ["resumes.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["round_profile_id"], ["round_profiles.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_interview_configs_company_id"), "interview_configs", ["company_id"], unique=False
    )
    op.create_index(
        op.f("ix_interview_configs_profile_id"), "interview_configs", ["profile_id"], unique=False
    )
    op.create_index(
        op.f("ix_interview_configs_resume_id"), "interview_configs", ["resume_id"], unique=False
    )
    op.create_index(
        op.f("ix_interview_configs_round_profile_id"),
        "interview_configs",
        ["round_profile_id"],
        unique=False,
    )
    op.create_table(
        "question_tag_links",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("question_id", sa.Uuid(), nullable=False),
        sa.Column("tag_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["question_id"], ["questions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tag_id"], ["question_tags.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("question_id", "tag_id", name="uq_question_tag_link"),
    )
    op.create_index(
        op.f("ix_question_tag_links_question_id"),
        "question_tag_links",
        ["question_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_question_tag_links_tag_id"), "question_tag_links", ["tag_id"], unique=False
    )
    op.create_table(
        "question_variants",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("question_id", sa.Uuid(), nullable=False),
        sa.Column("prompt", sa.Text(), nullable=False),
        sa.Column("variant_type", sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
        sa.ForeignKeyConstraint(["question_id"], ["questions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_question_variants_question_id"), "question_variants", ["question_id"], unique=False
    )
    op.create_table(
        "resume_claims",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("resume_id", sa.Uuid(), nullable=False),
        sa.Column("section_id", sa.Uuid(), nullable=True),
        sa.Column("claim_type", sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("source_span", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(["resume_id"], ["resumes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["section_id"], ["resume_sections.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_resume_claims_claim_type"), "resume_claims", ["claim_type"], unique=False
    )
    op.create_index(
        op.f("ix_resume_claims_resume_id"), "resume_claims", ["resume_id"], unique=False
    )
    op.create_index(
        op.f("ix_resume_claims_section_id"), "resume_claims", ["section_id"], unique=False
    )
    op.create_table(
        "interview_plans",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("config_id", sa.Uuid(), nullable=False),
        sa.Column("style_pack_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("total_minutes", sa.Integer(), nullable=False),
        sa.Column("plan_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=True),
        sa.Column("frozen_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["config_id"], ["interview_configs.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["style_pack_id"], ["company_style_packs.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_interview_plans_config_id"), "interview_plans", ["config_id"], unique=False
    )
    op.create_index(op.f("ix_interview_plans_status"), "interview_plans", ["status"], unique=False)
    op.create_index(
        op.f("ix_interview_plans_style_pack_id"), "interview_plans", ["style_pack_id"], unique=False
    )
    op.create_table(
        "interview_sessions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("profile_id", sa.Uuid(), nullable=False),
        sa.Column("plan_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("current_question_sequence", sa.Integer(), nullable=True),
        sa.Column("last_event_sequence", sa.Integer(), nullable=False),
        sa.Column("failure_code", sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
        sa.ForeignKeyConstraint(["plan_id"], ["interview_plans.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["profile_id"], ["user_profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_interview_sessions_plan_id"), "interview_sessions", ["plan_id"], unique=False
    )
    op.create_index(
        op.f("ix_interview_sessions_profile_id"), "interview_sessions", ["profile_id"], unique=False
    )
    op.create_index(
        op.f("ix_interview_sessions_status"), "interview_sessions", ["status"], unique=False
    )
    op.create_table(
        "plan_questions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("plan_id", sa.Uuid(), nullable=False),
        sa.Column("question_id", sa.Uuid(), nullable=True),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("source_type", sa.String(length=32), nullable=False),
        sa.Column("source_ref", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("prompt_snapshot", sa.Text(), nullable=False),
        sa.Column("capability_tags", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("allocated_seconds", sa.Integer(), nullable=False),
        sa.Column("follow_up_budget", sa.Integer(), nullable=False),
        sa.Column("selection_reason", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(["plan_id"], ["interview_plans.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["question_id"], ["questions.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("plan_id", "sequence", name="uq_plan_question_sequence"),
    )
    op.create_index(op.f("ix_plan_questions_plan_id"), "plan_questions", ["plan_id"], unique=False)
    op.create_index(
        op.f("ix_plan_questions_question_id"), "plan_questions", ["question_id"], unique=False
    )
    op.create_index(
        op.f("ix_plan_questions_source_type"), "plan_questions", ["source_type"], unique=False
    )
    op.create_table(
        "context_snapshots",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("agent_role", sa.String(length=32), nullable=False),
        sa.Column("model_connection_id", sa.Uuid(), nullable=True),
        sa.Column(
            "prompt_schema_version", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False
        ),
        sa.Column("included_refs", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("excluded_refs", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("token_by_layer", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("count_method", sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
        sa.Column("compaction_level", sa.Integer(), nullable=False),
        sa.Column(
            "provider_request_id", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True
        ),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["model_connection_id"], ["model_connections.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["session_id"], ["interview_sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_context_snapshots_agent_role"), "context_snapshots", ["agent_role"], unique=False
    )
    op.create_index(
        op.f("ix_context_snapshots_model_connection_id"),
        "context_snapshots",
        ["model_connection_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_context_snapshots_provider_request_id"),
        "context_snapshots",
        ["provider_request_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_context_snapshots_session_id"), "context_snapshots", ["session_id"], unique=False
    )
    op.create_table(
        "conversation_segments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("plan_question_id", sa.Uuid(), nullable=True),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("start_message_sequence", sa.Integer(), nullable=False),
        sa.Column("end_message_sequence", sa.Integer(), nullable=True),
        sa.Column("token_count", sa.Integer(), nullable=False),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["plan_question_id"], ["plan_questions.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["session_id"], ["interview_sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session_id", "sequence", name="uq_conversation_segment_sequence"),
    )
    op.create_index(
        op.f("ix_conversation_segments_plan_question_id"),
        "conversation_segments",
        ["plan_question_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_conversation_segments_session_id"),
        "conversation_segments",
        ["session_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_conversation_segments_status"), "conversation_segments", ["status"], unique=False
    )
    op.create_table(
        "evaluation_reports",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("overall_anchor", sa.String(length=32), nullable=False),
        sa.Column("overview", sa.Text(), nullable=True),
        sa.Column("strengths", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("gaps", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("action_plan", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("trend_comparison", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("evaluator_model_connection_id", sa.Uuid(), nullable=True),
        sa.Column("failure_code", sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
        sa.ForeignKeyConstraint(
            ["evaluator_model_connection_id"], ["model_connections.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["session_id"], ["interview_sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_evaluation_reports_evaluator_model_connection_id"),
        "evaluation_reports",
        ["evaluator_model_connection_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_evaluation_reports_overall_anchor"),
        "evaluation_reports",
        ["overall_anchor"],
        unique=False,
    )
    op.create_index(
        op.f("ix_evaluation_reports_session_id"), "evaluation_reports", ["session_id"], unique=True
    )
    op.create_index(
        op.f("ix_evaluation_reports_status"), "evaluation_reports", ["status"], unique=False
    )
    op.create_table(
        "interview_context_states",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("current_plan_question_id", sa.Uuid(), nullable=True),
        sa.Column("current_follow_up_index", sa.Integer(), nullable=False),
        sa.Column(
            "completed_question_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("unresolved_points", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("state_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("token_count", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["current_plan_question_id"], ["plan_questions.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["session_id"], ["interview_sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_interview_context_states_current_plan_question_id"),
        "interview_context_states",
        ["current_plan_question_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_interview_context_states_session_id"),
        "interview_context_states",
        ["session_id"],
        unique=True,
    )
    op.create_table(
        "summary_bundles",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("summary_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("covered_start_sequence", sa.Integer(), nullable=False),
        sa.Column("covered_end_sequence", sa.Integer(), nullable=False),
        sa.Column("content", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("token_count", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["session_id"], ["interview_sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_summary_bundles_session_id"), "summary_bundles", ["session_id"], unique=False
    )
    op.create_table(
        "context_summaries",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("segment_id", sa.Uuid(), nullable=False),
        sa.Column("summary_version", sa.Integer(), nullable=False),
        sa.Column("content", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("evidence_message_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("schema_version", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
        sa.Column("summarizer_model_connection_id", sa.Uuid(), nullable=True),
        sa.Column("token_count", sa.Integer(), nullable=False),
        sa.Column("validation_status", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(["segment_id"], ["conversation_segments.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["summarizer_model_connection_id"], ["model_connections.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("segment_id", "summary_version", name="uq_context_summary_version"),
    )
    op.create_index(
        op.f("ix_context_summaries_segment_id"), "context_summaries", ["segment_id"], unique=False
    )
    op.create_index(
        op.f("ix_context_summaries_summarizer_model_connection_id"),
        "context_summaries",
        ["summarizer_model_connection_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_context_summaries_validation_status"),
        "context_summaries",
        ["validation_status"],
        unique=False,
    )
    op.create_table(
        "dimension_evaluations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("report_id", sa.Uuid(), nullable=False),
        sa.Column("dimension", sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
        sa.Column("anchor", sa.String(length=32), nullable=False),
        sa.Column("evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("gaps", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("action", sa.Text(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(["report_id"], ["evaluation_reports.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("report_id", "dimension", name="uq_dimension_evaluation"),
    )
    op.create_index(
        op.f("ix_dimension_evaluations_anchor"), "dimension_evaluations", ["anchor"], unique=False
    )
    op.create_index(
        op.f("ix_dimension_evaluations_dimension"),
        "dimension_evaluations",
        ["dimension"],
        unique=False,
    )
    op.create_index(
        op.f("ix_dimension_evaluations_report_id"),
        "dimension_evaluations",
        ["report_id"],
        unique=False,
    )
    op.create_table(
        "interview_messages",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("plan_question_id", sa.Uuid(), nullable=True),
        sa.Column("segment_id", sa.Uuid(), nullable=True),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("confirmed", sa.Boolean(), nullable=False),
        sa.Column("token_count", sa.Integer(), nullable=True),
        sa.Column(
            "provider_message_id", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True
        ),
        sa.Column("message_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(["plan_question_id"], ["plan_questions.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["segment_id"], ["conversation_segments.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["session_id"], ["interview_sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session_id", "sequence", name="uq_interview_message_sequence"),
    )
    op.create_index(
        op.f("ix_interview_messages_plan_question_id"),
        "interview_messages",
        ["plan_question_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_interview_messages_role"), "interview_messages", ["role"], unique=False
    )
    op.create_index(
        op.f("ix_interview_messages_segment_id"), "interview_messages", ["segment_id"], unique=False
    )
    op.create_index(
        op.f("ix_interview_messages_session_id"), "interview_messages", ["session_id"], unique=False
    )
    op.create_table(
        "memory_usages",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("memory_id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("context_snapshot_id", sa.Uuid(), nullable=True),
        sa.Column("agent_role", sa.String(length=32), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["context_snapshot_id"], ["context_snapshots.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["memory_id"], ["memory_items.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["session_id"], ["interview_sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_memory_usages_agent_role"), "memory_usages", ["agent_role"], unique=False
    )
    op.create_index(
        op.f("ix_memory_usages_context_snapshot_id"),
        "memory_usages",
        ["context_snapshot_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_memory_usages_memory_id"), "memory_usages", ["memory_id"], unique=False
    )
    op.create_index(
        op.f("ix_memory_usages_session_id"), "memory_usages", ["session_id"], unique=False
    )
    op.create_table(
        "question_evaluations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("report_id", sa.Uuid(), nullable=False),
        sa.Column("plan_question_id", sa.Uuid(), nullable=False),
        sa.Column("anchor", sa.String(length=32), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("gaps", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("actions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(["plan_question_id"], ["plan_questions.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["report_id"], ["evaluation_reports.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("report_id", "plan_question_id", name="uq_question_evaluation"),
    )
    op.create_index(
        op.f("ix_question_evaluations_anchor"), "question_evaluations", ["anchor"], unique=False
    )
    op.create_index(
        op.f("ix_question_evaluations_plan_question_id"),
        "question_evaluations",
        ["plan_question_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_question_evaluations_report_id"),
        "question_evaluations",
        ["report_id"],
        unique=False,
    )
    op.create_table(
        "answer_attachments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("message_id", sa.Uuid(), nullable=False),
        sa.Column("attachment_type", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
        sa.Column("filename", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column("mime_type", sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
        sa.Column("language", sqlmodel.sql.sqltypes.AutoString(length=80), nullable=True),
        sa.Column("storage_path", sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("attachment_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(["message_id"], ["interview_messages.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_answer_attachments_attachment_type"),
        "answer_attachments",
        ["attachment_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_answer_attachments_message_id"), "answer_attachments", ["message_id"], unique=False
    )
    op.create_table(
        "memory_sources",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("memory_id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=True),
        sa.Column("message_id", sa.Uuid(), nullable=True),
        sa.Column("source_type", sqlmodel.sql.sqltypes.AutoString(length=48), nullable=False),
        sa.Column("evidence_excerpt", sa.Text(), nullable=True),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["memory_id"], ["memory_items.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["message_id"], ["interview_messages.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["session_id"], ["interview_sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_memory_sources_memory_id"), "memory_sources", ["memory_id"], unique=False
    )
    op.create_index(
        op.f("ix_memory_sources_message_id"), "memory_sources", ["message_id"], unique=False
    )
    op.create_index(
        op.f("ix_memory_sources_session_id"), "memory_sources", ["session_id"], unique=False
    )
    op.create_index(
        op.f("ix_memory_sources_source_type"), "memory_sources", ["source_type"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_memory_sources_source_type"), table_name="memory_sources")
    op.drop_index(op.f("ix_memory_sources_session_id"), table_name="memory_sources")
    op.drop_index(op.f("ix_memory_sources_message_id"), table_name="memory_sources")
    op.drop_index(op.f("ix_memory_sources_memory_id"), table_name="memory_sources")
    op.drop_table("memory_sources")
    op.drop_index(op.f("ix_answer_attachments_message_id"), table_name="answer_attachments")
    op.drop_index(op.f("ix_answer_attachments_attachment_type"), table_name="answer_attachments")
    op.drop_table("answer_attachments")
    op.drop_index(op.f("ix_question_evaluations_report_id"), table_name="question_evaluations")
    op.drop_index(
        op.f("ix_question_evaluations_plan_question_id"), table_name="question_evaluations"
    )
    op.drop_index(op.f("ix_question_evaluations_anchor"), table_name="question_evaluations")
    op.drop_table("question_evaluations")
    op.drop_index(op.f("ix_memory_usages_session_id"), table_name="memory_usages")
    op.drop_index(op.f("ix_memory_usages_memory_id"), table_name="memory_usages")
    op.drop_index(op.f("ix_memory_usages_context_snapshot_id"), table_name="memory_usages")
    op.drop_index(op.f("ix_memory_usages_agent_role"), table_name="memory_usages")
    op.drop_table("memory_usages")
    op.drop_index(op.f("ix_interview_messages_session_id"), table_name="interview_messages")
    op.drop_index(op.f("ix_interview_messages_segment_id"), table_name="interview_messages")
    op.drop_index(op.f("ix_interview_messages_role"), table_name="interview_messages")
    op.drop_index(op.f("ix_interview_messages_plan_question_id"), table_name="interview_messages")
    op.drop_table("interview_messages")
    op.drop_index(op.f("ix_dimension_evaluations_report_id"), table_name="dimension_evaluations")
    op.drop_index(op.f("ix_dimension_evaluations_dimension"), table_name="dimension_evaluations")
    op.drop_index(op.f("ix_dimension_evaluations_anchor"), table_name="dimension_evaluations")
    op.drop_table("dimension_evaluations")
    op.drop_index(op.f("ix_context_summaries_validation_status"), table_name="context_summaries")
    op.drop_index(
        op.f("ix_context_summaries_summarizer_model_connection_id"), table_name="context_summaries"
    )
    op.drop_index(op.f("ix_context_summaries_segment_id"), table_name="context_summaries")
    op.drop_table("context_summaries")
    op.drop_index(op.f("ix_summary_bundles_session_id"), table_name="summary_bundles")
    op.drop_table("summary_bundles")
    op.drop_index(
        op.f("ix_interview_context_states_session_id"), table_name="interview_context_states"
    )
    op.drop_index(
        op.f("ix_interview_context_states_current_plan_question_id"),
        table_name="interview_context_states",
    )
    op.drop_table("interview_context_states")
    op.drop_index(op.f("ix_evaluation_reports_status"), table_name="evaluation_reports")
    op.drop_index(op.f("ix_evaluation_reports_session_id"), table_name="evaluation_reports")
    op.drop_index(op.f("ix_evaluation_reports_overall_anchor"), table_name="evaluation_reports")
    op.drop_index(
        op.f("ix_evaluation_reports_evaluator_model_connection_id"), table_name="evaluation_reports"
    )
    op.drop_table("evaluation_reports")
    op.drop_index(op.f("ix_conversation_segments_status"), table_name="conversation_segments")
    op.drop_index(op.f("ix_conversation_segments_session_id"), table_name="conversation_segments")
    op.drop_index(
        op.f("ix_conversation_segments_plan_question_id"), table_name="conversation_segments"
    )
    op.drop_table("conversation_segments")
    op.drop_index(op.f("ix_context_snapshots_session_id"), table_name="context_snapshots")
    op.drop_index(op.f("ix_context_snapshots_provider_request_id"), table_name="context_snapshots")
    op.drop_index(op.f("ix_context_snapshots_model_connection_id"), table_name="context_snapshots")
    op.drop_index(op.f("ix_context_snapshots_agent_role"), table_name="context_snapshots")
    op.drop_table("context_snapshots")
    op.drop_index(op.f("ix_plan_questions_source_type"), table_name="plan_questions")
    op.drop_index(op.f("ix_plan_questions_question_id"), table_name="plan_questions")
    op.drop_index(op.f("ix_plan_questions_plan_id"), table_name="plan_questions")
    op.drop_table("plan_questions")
    op.drop_index(op.f("ix_interview_sessions_status"), table_name="interview_sessions")
    op.drop_index(op.f("ix_interview_sessions_profile_id"), table_name="interview_sessions")
    op.drop_index(op.f("ix_interview_sessions_plan_id"), table_name="interview_sessions")
    op.drop_table("interview_sessions")
    op.drop_index(op.f("ix_interview_plans_style_pack_id"), table_name="interview_plans")
    op.drop_index(op.f("ix_interview_plans_status"), table_name="interview_plans")
    op.drop_index(op.f("ix_interview_plans_config_id"), table_name="interview_plans")
    op.drop_table("interview_plans")
    op.drop_index(op.f("ix_resume_claims_section_id"), table_name="resume_claims")
    op.drop_index(op.f("ix_resume_claims_resume_id"), table_name="resume_claims")
    op.drop_index(op.f("ix_resume_claims_claim_type"), table_name="resume_claims")
    op.drop_table("resume_claims")
    op.drop_index(op.f("ix_question_variants_question_id"), table_name="question_variants")
    op.drop_table("question_variants")
    op.drop_index(op.f("ix_question_tag_links_tag_id"), table_name="question_tag_links")
    op.drop_index(op.f("ix_question_tag_links_question_id"), table_name="question_tag_links")
    op.drop_table("question_tag_links")
    op.drop_index(op.f("ix_interview_configs_round_profile_id"), table_name="interview_configs")
    op.drop_index(op.f("ix_interview_configs_resume_id"), table_name="interview_configs")
    op.drop_index(op.f("ix_interview_configs_profile_id"), table_name="interview_configs")
    op.drop_index(op.f("ix_interview_configs_company_id"), table_name="interview_configs")
    op.drop_table("interview_configs")
    op.drop_index(op.f("ix_round_profiles_style_pack_id"), table_name="round_profiles")
    op.drop_table("round_profiles")
    op.drop_index(op.f("ix_resume_sections_section_type"), table_name="resume_sections")
    op.drop_index(op.f("ix_resume_sections_resume_id"), table_name="resume_sections")
    op.drop_table("resume_sections")
    op.drop_index(op.f("ix_questions_status"), table_name="questions")
    op.drop_index(op.f("ix_questions_source_type"), table_name="questions")
    op.drop_index(op.f("ix_questions_question_type"), table_name="questions")
    op.drop_index(op.f("ix_questions_normalized_hash"), table_name="questions")
    op.drop_index(op.f("ix_questions_difficulty"), table_name="questions")
    op.drop_index(op.f("ix_questions_bank_id"), table_name="questions")
    op.drop_table("questions")
    op.drop_index(op.f("ix_model_role_bindings_role"), table_name="model_role_bindings")
    op.drop_index(op.f("ix_model_role_bindings_profile_id"), table_name="model_role_bindings")
    op.drop_index(op.f("ix_model_role_bindings_connection_id"), table_name="model_role_bindings")
    op.drop_table("model_role_bindings")
    op.drop_index(op.f("ix_memory_conflicts_status"), table_name="memory_conflicts")
    op.drop_index(op.f("ix_memory_conflicts_memory_id"), table_name="memory_conflicts")
    op.drop_index(op.f("ix_memory_conflicts_conflicting_memory_id"), table_name="memory_conflicts")
    op.drop_table("memory_conflicts")
    op.drop_index(op.f("ix_evidence_items_style_pack_id"), table_name="evidence_items")
    op.drop_index(op.f("ix_evidence_items_source_hash"), table_name="evidence_items")
    op.drop_index(op.f("ix_evidence_items_field_path"), table_name="evidence_items")
    op.drop_table("evidence_items")
    op.drop_index(op.f("ix_resumes_profile_id"), table_name="resumes")
    op.drop_index(op.f("ix_resumes_parse_status"), table_name="resumes")
    op.drop_index(op.f("ix_resumes_content_hash"), table_name="resumes")
    op.drop_table("resumes")
    op.drop_index(op.f("ix_question_banks_visibility"), table_name="question_banks")
    op.drop_index(op.f("ix_question_banks_profile_id"), table_name="question_banks")
    op.drop_table("question_banks")
    op.drop_index(op.f("ix_model_connections_status"), table_name="model_connections")
    op.drop_index(op.f("ix_model_connections_provider_type"), table_name="model_connections")
    op.drop_index(op.f("ix_model_connections_profile_id"), table_name="model_connections")
    op.drop_index(op.f("ix_model_connections_model_name"), table_name="model_connections")
    op.drop_table("model_connections")
    op.drop_index(op.f("ix_memory_items_status"), table_name="memory_items")
    op.drop_index(op.f("ix_memory_items_profile_id"), table_name="memory_items")
    op.drop_index(op.f("ix_memory_items_pinned"), table_name="memory_items")
    op.drop_index(op.f("ix_memory_items_memory_type"), table_name="memory_items")
    op.drop_index(op.f("ix_memory_items_canonical_key"), table_name="memory_items")
    op.drop_table("memory_items")
    op.drop_index(op.f("ix_company_style_packs_visibility"), table_name="company_style_packs")
    op.drop_index(op.f("ix_company_style_packs_status"), table_name="company_style_packs")
    op.drop_index(op.f("ix_company_style_packs_company_id"), table_name="company_style_packs")
    op.drop_table("company_style_packs")
    op.drop_index(op.f("ix_background_jobs_status"), table_name="background_jobs")
    op.drop_index(op.f("ix_background_jobs_profile_id"), table_name="background_jobs")
    op.drop_index(op.f("ix_background_jobs_job_type"), table_name="background_jobs")
    op.drop_index(op.f("ix_background_jobs_idempotency_key"), table_name="background_jobs")
    op.drop_index(op.f("ix_background_jobs_available_at"), table_name="background_jobs")
    op.drop_table("background_jobs")
    op.drop_table("user_profiles")
    op.drop_index(op.f("ix_question_tags_slug"), table_name="question_tags")
    op.drop_index(op.f("ix_question_tags_name"), table_name="question_tags")
    op.drop_index(op.f("ix_question_tags_category"), table_name="question_tags")
    op.drop_table("question_tags")
    op.drop_index(op.f("ix_companies_slug"), table_name="companies")
    op.drop_index(op.f("ix_companies_name"), table_name="companies")
    op.drop_table("companies")
    # ### end Alembic commands ###
